### ISSUE TITLE
Can you give an example for cmake correlation_cost in Windows

### ISSUE THREAD

**Issue by syzlhh** [PatWie/tensorflow-recipes#2]
Thank you for your great work. Can you give an example for make the "tensorflow-recipes/OpticalFlow/user_ops/" on windows 10 platform.

**Comment by PatWie** [comment]
There is a related issue for windows:

https://github.com/PatWie/tensorflow-cmake/issues/31

I will not support windows in this repo. Hopefully, we can find a workaround in the other issue.

**Comment by syzlhh** [comment]
Thank you. Can you share the compiled correlation_cost_op.so?

**Comment by PatWie** [comment]
I doubt this would work across different systems. But anyway, here you go:

[user_ops.zip](https://github.com/PatWie/tensorflow-recipes/files/3149318/user_ops.zip)
